TYPE=VIEW
query=select `metrics`.`brand_id` AS `id`,`metrics`.`brand_name` AS `name`,cast(`metrics`.`coupon_created` as date) AS `dates`,sum(`metrics`.`coupons_generated`) AS `coupons_generated`,sum(`metrics`.`coupons_redimed`) AS `coupons_redimed`,sum(`metrics`.`coupons_expired`) AS `coupons_expired` from (select `c`.`brand_id` AS `brand_id`,`c`.`brand_name` AS `brand_name`,`c`.`coupon_created` AS `coupon_created`,count(`c`.`coupon_id`) AS `coupons_generated`,0 AS `coupons_redimed`,0 AS `coupons_expired` from `tablita`.`vwCoupon` `c` where (`c`.`coupon_status` <> \'X\') group by `c`.`brand_id`,`c`.`brand_name`,`c`.`coupon_created` union all select `c`.`brand_id` AS `brand_id`,`c`.`brand_name` AS `brand_name`,`c`.`coupon_created` AS `coupon_created`,0 AS `coupons_generated`,count(`c`.`coupon_id`) AS `coupons_redimed`,0 AS `coupons_expired` from `tablita`.`vwCoupon` `c` where (`c`.`coupon_status` = \'R\') group by `c`.`brand_id`,`c`.`brand_name`,`c`.`coupon_created` union all select `c`.`brand_id` AS `brand_id`,`c`.`brand_name` AS `brand_name`,`c`.`coupon_created` AS `coupon_created`,0 AS `coupons_generated`,0 AS `coupons_redimed`,count(`c`.`coupon_id`) AS `coupons_expired` from `tablita`.`vwCoupon` `c` where ((`c`.`coupon_expire` < now()) and (`c`.`coupon_status` not in (\'X\',\'R\'))) group by `c`.`brand_id`,`c`.`brand_name`,`c`.`coupon_created`) `metrics` group by `metrics`.`brand_id`,`metrics`.`brand_name`,cast(`metrics`.`coupon_created` as date)
md5=8df7f2ed1dd89309b1c1ff7a852f0ebc
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=1
with_check_option=0
timestamp=2021-06-04 23:21:29
create-version=1
source=select \n `metrics`.`brand_id` AS `id`,\n `metrics`.`brand_name` AS `name`,\n cast(`metrics`.`coupon_created` as date) AS `dates`,\n sum(`metrics`.`coupons_generated`) AS `coupons_generated`,\n sum(`metrics`.`coupons_redimed`) AS `coupons_redimed`,\n sum(`metrics`.`coupons_expired`) AS `coupons_expired` \n from \n (\n select \n `c`.`brand_id` AS `brand_id`,\n `c`.`brand_name` AS `brand_name`,\n `c`.`coupon_created` AS `coupon_created`,\n count(`c`.`coupon_id`) AS `coupons_generated`,\n 0 AS `coupons_redimed`,\n 0 AS `coupons_expired` \n from \n `tablita`.`vwCoupon` `c` \n where \n (`c`.`coupon_status` <> \'X\') \n group by \n `c`.`brand_id`,`c`.`brand_name`,`c`.`coupon_created` union all \n select \n `c`.`brand_id` AS `brand_id`,\n `c`.`brand_name` AS `brand_name`,\n `c`.`coupon_created` AS `coupon_created`,\n 0 AS `coupons_generated`,\n count(`c`.`coupon_id`) AS `coupons_redimed`,\n 0 AS `coupons_expired` \n from \n `tablita`.`vwCoupon` `c` \n where \n (`c`.`coupon_status` = \'R\') \n group by \n `c`.`brand_id`,`c`.`brand_name`,`c`.`coupon_created` union all \n select \n `c`.`brand_id` AS `brand_id`,\n `c`.`brand_name` AS `brand_name`,\n `c`.`coupon_created` AS `coupon_created`,\n 0 AS `coupons_generated`,\n 0 AS `coupons_redimed`,\n count(`c`.`coupon_id`) AS `coupons_expired` \n from \n `tablita`.`vwCoupon` `c` \n where \n ((`c`.`coupon_expire` < now()) and (`c`.`coupon_status` not in (\'X\',\'R\'))) \n group by \n `c`.`brand_id`,`c`.`brand_name`,`c`.`coupon_created`) `metrics` \n group by \n `metrics`.`brand_id`,`metrics`.`brand_name`,cast(`metrics`.`coupon_created` as date)
client_cs_name=latin1
connection_cl_name=latin1_swedish_ci
view_body_utf8=select `metrics`.`brand_id` AS `id`,`metrics`.`brand_name` AS `name`,cast(`metrics`.`coupon_created` as date) AS `dates`,sum(`metrics`.`coupons_generated`) AS `coupons_generated`,sum(`metrics`.`coupons_redimed`) AS `coupons_redimed`,sum(`metrics`.`coupons_expired`) AS `coupons_expired` from (select `c`.`brand_id` AS `brand_id`,`c`.`brand_name` AS `brand_name`,`c`.`coupon_created` AS `coupon_created`,count(`c`.`coupon_id`) AS `coupons_generated`,0 AS `coupons_redimed`,0 AS `coupons_expired` from `tablita`.`vwCoupon` `c` where (`c`.`coupon_status` <> \'X\') group by `c`.`brand_id`,`c`.`brand_name`,`c`.`coupon_created` union all select `c`.`brand_id` AS `brand_id`,`c`.`brand_name` AS `brand_name`,`c`.`coupon_created` AS `coupon_created`,0 AS `coupons_generated`,count(`c`.`coupon_id`) AS `coupons_redimed`,0 AS `coupons_expired` from `tablita`.`vwCoupon` `c` where (`c`.`coupon_status` = \'R\') group by `c`.`brand_id`,`c`.`brand_name`,`c`.`coupon_created` union all select `c`.`brand_id` AS `brand_id`,`c`.`brand_name` AS `brand_name`,`c`.`coupon_created` AS `coupon_created`,0 AS `coupons_generated`,0 AS `coupons_redimed`,count(`c`.`coupon_id`) AS `coupons_expired` from `tablita`.`vwCoupon` `c` where ((`c`.`coupon_expire` < now()) and (`c`.`coupon_status` not in (\'X\',\'R\'))) group by `c`.`brand_id`,`c`.`brand_name`,`c`.`coupon_created`) `metrics` group by `metrics`.`brand_id`,`metrics`.`brand_name`,cast(`metrics`.`coupon_created` as date)
