TYPE=VIEW
query=select `metrics`.`campaign_id` AS `id`,`metrics`.`campaign_name` AS `name`,cast(`metrics`.`coupon_created` as date) AS `dates`,sum(`metrics`.`coupons_generated`) AS `coupons_generated`,sum(`metrics`.`coupons_redimed`) AS `coupons_redimed`,sum(`metrics`.`coupons_expired`) AS `coupons_expired` from (select `c`.`campaign_id` AS `campaign_id`,`c`.`campaign_name` AS `campaign_name`,`c`.`coupon_created` AS `coupon_created`,count(`c`.`coupon_id`) AS `coupons_generated`,0 AS `coupons_redimed`,0 AS `coupons_expired` from `tablita`.`vwCoupon` `c` where (`c`.`coupon_status` <> \'X\') group by `c`.`campaign_id`,`c`.`campaign_name`,`c`.`coupon_created` union all select `c`.`coupon_created` AS `coupon_created`,`c`.`campaign_id` AS `campaign_id`,`c`.`campaign_name` AS `campaign_name`,0 AS `coupons_generated`,count(`c`.`coupon_id`) AS `coupons_redimed`,0 AS `coupons_expired` from `tablita`.`vwCoupon` `c` where (`c`.`coupon_status` = \'R\') group by `c`.`campaign_id`,`c`.`campaign_name`,`c`.`coupon_created` union all select `c`.`campaign_id` AS `campaign_id`,`c`.`campaign_name` AS `campaign_name`,`c`.`coupon_created` AS `coupon_created`,0 AS `coupons_generated`,0 AS `coupons_redimed`,count(`c`.`coupon_id`) AS `coupons_expired` from `tablita`.`vwCoupon` `c` where ((`c`.`coupon_expire` < now()) and (`c`.`coupon_status` not in (\'X\',\'R\'))) group by `c`.`campaign_id`,`c`.`campaign_name`,`c`.`coupon_created`) `metrics` where (`metrics`.`campaign_id` is not null) group by `metrics`.`campaign_id`,`metrics`.`campaign_name`,cast(`metrics`.`coupon_created` as date)
md5=eaaefe18e2b4f2db27f2d04d29bfb46f
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=1
with_check_option=0
timestamp=2021-06-04 23:21:29
create-version=1
source=select \n `metrics`.`campaign_id` AS `id`,\n `metrics`.`campaign_name` AS `name`,\n cast(`metrics`.`coupon_created` as date) AS `dates`,\n sum(`metrics`.`coupons_generated`) AS `coupons_generated`,\n sum(`metrics`.`coupons_redimed`) AS `coupons_redimed`,\n sum(`metrics`.`coupons_expired`) AS `coupons_expired` \n from \n (\n select \n `c`.`campaign_id` AS `campaign_id`,\n `c`.`campaign_name` AS `campaign_name`,\n `c`.`coupon_created` AS `coupon_created`,\n count(`c`.`coupon_id`) AS `coupons_generated`,\n 0 AS `coupons_redimed`,\n 0 AS `coupons_expired` \n from \n `tablita`.`vwCoupon` `c` \n where \n (`c`.`coupon_status` <> \'X\') \n group by \n `c`.`campaign_id`,`c`.`campaign_name`,`c`.`coupon_created` union all \n select \n `c`.`coupon_created` AS `coupon_created`,\n `c`.`campaign_id` AS `campaign_id`,\n `c`.`campaign_name` AS `campaign_name`,\n 0 AS `coupons_generated`,\n count(`c`.`coupon_id`) AS `coupons_redimed`,\n 0 AS `coupons_expired` \n from \n `tablita`.`vwCoupon` `c` \n where \n (`c`.`coupon_status` = \'R\') \n group by \n `c`.`campaign_id`,`c`.`campaign_name`,`c`.`coupon_created` union all \n select \n `c`.`campaign_id` AS `campaign_id`,\n `c`.`campaign_name` AS `campaign_name`,\n `c`.`coupon_created` AS `coupon_created`,\n 0 AS `coupons_generated`,\n 0 AS `coupons_redimed`,\n count(`c`.`coupon_id`) AS `coupons_expired` \n from \n `tablita`.`vwCoupon` `c` \n where \n ((`c`.`coupon_expire` < now()) and (`c`.`coupon_status` not in (\'X\',\'R\'))) \n group by \n `c`.`campaign_id`,`c`.`campaign_name`,`c`.`coupon_created`) `metrics` \n where \n (`metrics`.`campaign_id` is not null) \n group by \n `metrics`.`campaign_id`,`metrics`.`campaign_name`,cast(`metrics`.`coupon_created` as date)
client_cs_name=latin1
connection_cl_name=latin1_swedish_ci
view_body_utf8=select `metrics`.`campaign_id` AS `id`,`metrics`.`campaign_name` AS `name`,cast(`metrics`.`coupon_created` as date) AS `dates`,sum(`metrics`.`coupons_generated`) AS `coupons_generated`,sum(`metrics`.`coupons_redimed`) AS `coupons_redimed`,sum(`metrics`.`coupons_expired`) AS `coupons_expired` from (select `c`.`campaign_id` AS `campaign_id`,`c`.`campaign_name` AS `campaign_name`,`c`.`coupon_created` AS `coupon_created`,count(`c`.`coupon_id`) AS `coupons_generated`,0 AS `coupons_redimed`,0 AS `coupons_expired` from `tablita`.`vwCoupon` `c` where (`c`.`coupon_status` <> \'X\') group by `c`.`campaign_id`,`c`.`campaign_name`,`c`.`coupon_created` union all select `c`.`coupon_created` AS `coupon_created`,`c`.`campaign_id` AS `campaign_id`,`c`.`campaign_name` AS `campaign_name`,0 AS `coupons_generated`,count(`c`.`coupon_id`) AS `coupons_redimed`,0 AS `coupons_expired` from `tablita`.`vwCoupon` `c` where (`c`.`coupon_status` = \'R\') group by `c`.`campaign_id`,`c`.`campaign_name`,`c`.`coupon_created` union all select `c`.`campaign_id` AS `campaign_id`,`c`.`campaign_name` AS `campaign_name`,`c`.`coupon_created` AS `coupon_created`,0 AS `coupons_generated`,0 AS `coupons_redimed`,count(`c`.`coupon_id`) AS `coupons_expired` from `tablita`.`vwCoupon` `c` where ((`c`.`coupon_expire` < now()) and (`c`.`coupon_status` not in (\'X\',\'R\'))) group by `c`.`campaign_id`,`c`.`campaign_name`,`c`.`coupon_created`) `metrics` where (`metrics`.`campaign_id` is not null) group by `metrics`.`campaign_id`,`metrics`.`campaign_name`,cast(`metrics`.`coupon_created` as date)
