TYPE=VIEW
query=select `c`.`coupon_id` AS `coupon_id`,`c`.`coupon_codebar` AS `coupon_codebar`,`c`.`coupon_created` AS `coupon_created`,`c`.`coupon_status` AS `coupon_status`,`c`.`coupon_redimed` AS `coupon_redimed`,`c`.`coupon_redimed_file` AS `coupon_redimed_file`,`c`.`coupon_expire` AS `coupon_expire`,`c`.`coupon_device` AS `coupon_device`,`c`.`coupon_host` AS `coupon_host`,`c`.`coupon_ip` AS `coupon_ip`,`c`.`coupon_latitude` AS `coupon_latitude`,`c`.`coupon_longitude` AS `coupon_longitude`,`c`.`coupon_source` AS `coupon_source`,`mp`.`media_product_id` AS `media_product_id`,`mp`.`media_product_code` AS `media_product_code`,`b`.`brand_id` AS `brand_id`,`b`.`brand_name` AS `brand_name`,`p`.`product_id` AS `product_id`,`p`.`product_name` AS `product_name`,`m`.`media_id` AS `media_id`,`m`.`media_name` AS `media_name`,`ct`.`code_type_id` AS `code_type_id`,`ct`.`code_type_name` AS `code_type_name`,`cmmt`.`commerce_type_id` AS `commerce_type_id`,`cmmt`.`commerce_type_name` AS `commerce_type_name`,`cs`.`consummer_id` AS `consummer_id`,`cs`.`consummer_name` AS `consummer_name` from (((((((`tablita`.`coupon` `c` left join `tablita`.`media_product` `mp` on((`c`.`media_product_id` = `mp`.`media_product_id`))) left join `tablita`.`product` `p` on((`mp`.`product_id` = `p`.`product_id`))) left join `tablita`.`brand` `b` on((`p`.`brand_id` = `b`.`brand_id`))) left join `tablita`.`media` `m` on((`mp`.`media_id` = `m`.`media_id`))) left join `tablita`.`code_type` `ct` on((`mp`.`code_type_id` = `ct`.`code_type_id`))) left join `tablita`.`commerce_type` `cmmt` on((`c`.`commerce_type_id` = `cmmt`.`commerce_type_id`))) left join `tablita`.`consummer` `cs` on((`c`.`consummer_id` = `cs`.`consummer_id`))) where (`b`.`brand_id` = \'4c61acb4-ff31-46e0-8778-998f6098b37f\') order by `mp`.`media_product_code`,`c`.`coupon_created`
md5=3854a789d9c0e64926b5b58ec2b43580
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=1
with_check_option=0
timestamp=2021-06-04 23:21:26
create-version=1
source=select \n `c`.`coupon_id` AS `coupon_id`,\n `c`.`coupon_codebar` AS `coupon_codebar`,\n `c`.`coupon_created` AS `coupon_created`,\n `c`.`coupon_status` AS `coupon_status`,\n `c`.`coupon_redimed` AS `coupon_redimed`,\n `c`.`coupon_redimed_file` AS `coupon_redimed_file`,\n `c`.`coupon_expire` AS `coupon_expire`,\n `c`.`coupon_device` AS `coupon_device`,\n `c`.`coupon_host` AS `coupon_host`,\n `c`.`coupon_ip` AS `coupon_ip`,\n `c`.`coupon_latitude` AS `coupon_latitude`,\n `c`.`coupon_longitude` AS `coupon_longitude`,\n `c`.`coupon_source` AS `coupon_source`,\n `mp`.`media_product_id` AS `media_product_id`,\n `mp`.`media_product_code` AS `media_product_code`,\n `b`.`brand_id` AS `brand_id`,\n `b`.`brand_name` AS `brand_name`,\n `p`.`product_id` AS `product_id`,\n `p`.`product_name` AS `product_name`,\n `m`.`media_id` AS `media_id`,\n `m`.`media_name` AS `media_name`,\n `ct`.`code_type_id` AS `code_type_id`,\n `ct`.`code_type_name` AS `code_type_name`,\n `cmmt`.`commerce_type_id` AS `commerce_type_id`,\n `cmmt`.`commerce_type_name` AS `commerce_type_name`,\n `cs`.`consummer_id` AS `consummer_id`,\n `cs`.`consummer_name` AS `consummer_name` \n from \n (((((((`coupon` `c` left join `media_product` `mp` on((`c`.`media_product_id` = `mp`.`media_product_id`))) left join `product` `p` on((`mp`.`product_id` = `p`.`product_id`))) left join `brand` `b` on((`p`.`brand_id` = `b`.`brand_id`))) left join `media` `m` on((`mp`.`media_id` = `m`.`media_id`))) left join `code_type` `ct` on((`mp`.`code_type_id` = `ct`.`code_type_id`))) left join `commerce_type` `cmmt` on((`c`.`commerce_type_id` = `cmmt`.`commerce_type_id`))) left join `consummer` `cs` on((`c`.`consummer_id` = `cs`.`consummer_id`))) \n where \n (`b`.`brand_id` = \'4c61acb4-ff31-46e0-8778-998f6098b37f\') \n order by \n `mp`.`media_product_code`,`c`.`coupon_created`
client_cs_name=latin1
connection_cl_name=latin1_swedish_ci
view_body_utf8=select `c`.`coupon_id` AS `coupon_id`,`c`.`coupon_codebar` AS `coupon_codebar`,`c`.`coupon_created` AS `coupon_created`,`c`.`coupon_status` AS `coupon_status`,`c`.`coupon_redimed` AS `coupon_redimed`,`c`.`coupon_redimed_file` AS `coupon_redimed_file`,`c`.`coupon_expire` AS `coupon_expire`,`c`.`coupon_device` AS `coupon_device`,`c`.`coupon_host` AS `coupon_host`,`c`.`coupon_ip` AS `coupon_ip`,`c`.`coupon_latitude` AS `coupon_latitude`,`c`.`coupon_longitude` AS `coupon_longitude`,`c`.`coupon_source` AS `coupon_source`,`mp`.`media_product_id` AS `media_product_id`,`mp`.`media_product_code` AS `media_product_code`,`b`.`brand_id` AS `brand_id`,`b`.`brand_name` AS `brand_name`,`p`.`product_id` AS `product_id`,`p`.`product_name` AS `product_name`,`m`.`media_id` AS `media_id`,`m`.`media_name` AS `media_name`,`ct`.`code_type_id` AS `code_type_id`,`ct`.`code_type_name` AS `code_type_name`,`cmmt`.`commerce_type_id` AS `commerce_type_id`,`cmmt`.`commerce_type_name` AS `commerce_type_name`,`cs`.`consummer_id` AS `consummer_id`,`cs`.`consummer_name` AS `consummer_name` from (((((((`tablita`.`coupon` `c` left join `tablita`.`media_product` `mp` on((`c`.`media_product_id` = `mp`.`media_product_id`))) left join `tablita`.`product` `p` on((`mp`.`product_id` = `p`.`product_id`))) left join `tablita`.`brand` `b` on((`p`.`brand_id` = `b`.`brand_id`))) left join `tablita`.`media` `m` on((`mp`.`media_id` = `m`.`media_id`))) left join `tablita`.`code_type` `ct` on((`mp`.`code_type_id` = `ct`.`code_type_id`))) left join `tablita`.`commerce_type` `cmmt` on((`c`.`commerce_type_id` = `cmmt`.`commerce_type_id`))) left join `tablita`.`consummer` `cs` on((`c`.`consummer_id` = `cs`.`consummer_id`))) where (`b`.`brand_id` = \'4c61acb4-ff31-46e0-8778-998f6098b37f\') order by `mp`.`media_product_code`,`c`.`coupon_created`
