TYPE=VIEW
query=select `c`.`coupon_id` AS `coupon_id`,`c`.`media_product_id` AS `media_product_id`,`c`.`campaign_product_id` AS `campaign_product_id`,`c`.`coupon_codebar` AS `coupon_codebar`,`c`.`coupon_status` AS `coupon_status`,(case when isnull(`c`.`media_product_id`) then `p2`.`product_id` else `p`.`product_id` end) AS `product_id`,(case when isnull(`c`.`media_product_id`) then `p2`.`product_sku` else `p`.`product_sku` end) AS `product_sku`,(case when isnull(`c`.`media_product_id`) then `p2`.`product_name` else `p`.`product_name` end) AS `product_name`,`comm`.`consummer_name` AS `consummer_name`,`comm`.`consummer_identification` AS `consummer_identification`,`comm`.`consummer_email` AS `consummer_email`,`comm`.`consummer_phone` AS `consummer_phone` from (((((`tablita`.`coupon` `c` left join `tablita`.`media_product` `mp` on((`c`.`media_product_id` = `mp`.`media_product_id`))) left join `tablita`.`product` `p` on((`mp`.`product_id` = `p`.`product_id`))) left join `tablita`.`campaign_product` `cp` on((`c`.`campaign_product_id` = `cp`.`campaign_product_id`))) left join `tablita`.`product` `p2` on((`cp`.`product_id` = `p2`.`product_id`))) left join `tablita`.`consummer` `comm` on((`c`.`consummer_id` = `comm`.`consummer_id`))) where (`c`.`coupon_status` = \'R\') order by `c`.`coupon_id`
md5=3da043a8cd2b27f1b6e7bf380902122c
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=1
with_check_option=0
timestamp=2021-06-08 15:10:27
create-version=1
source=select \n    `c`.`coupon_id` AS `coupon_id`,\n    `c`.`media_product_id` AS `media_product_id`,\n    `c`.`campaign_product_id` AS `campaign_product_id`,\n    `c`.`coupon_codebar` AS `coupon_codebar`,\n    `c`.`coupon_status` AS `coupon_status`,\n    (case when isnull(`c`.`media_product_id`) then `p2`.`product_id` else `p`.`product_id` end) AS `product_id`,\n    (case when isnull(`c`.`media_product_id`) then `p2`.`product_sku` else `p`.`product_sku` end) AS `product_sku`,\n    (case when isnull(`c`.`media_product_id`) then `p2`.`product_name` else `p`.`product_name` end) AS `product_name`,\n    `comm`.`consummer_name` AS `consummer_name`,\n    `comm`.`consummer_identification` AS `consummer_identification`,\n    `comm`.`consummer_email` AS `consummer_email`,\n    `comm`.`consummer_phone` AS `consummer_phone` \n  from \n    (((((`coupon` `c` left join `media_product` `mp` on((`c`.`media_product_id` = `mp`.`media_product_id`))) left join `product` `p` on((`mp`.`product_id` = `p`.`product_id`))) left join `campaign_product` `cp` on((`c`.`campaign_product_id` = `cp`.`campaign_product_id`))) left join `product` `p2` on((`cp`.`product_id` = `p2`.`product_id`))) left join `consummer` `comm` on((`c`.`consummer_id` = `comm`.`consummer_id`))) \n  where \n    (`c`.`coupon_status` = \'R\') \n  order by \n    `c`.`coupon_id`
client_cs_name=latin1
connection_cl_name=latin1_swedish_ci
view_body_utf8=select `c`.`coupon_id` AS `coupon_id`,`c`.`media_product_id` AS `media_product_id`,`c`.`campaign_product_id` AS `campaign_product_id`,`c`.`coupon_codebar` AS `coupon_codebar`,`c`.`coupon_status` AS `coupon_status`,(case when isnull(`c`.`media_product_id`) then `p2`.`product_id` else `p`.`product_id` end) AS `product_id`,(case when isnull(`c`.`media_product_id`) then `p2`.`product_sku` else `p`.`product_sku` end) AS `product_sku`,(case when isnull(`c`.`media_product_id`) then `p2`.`product_name` else `p`.`product_name` end) AS `product_name`,`comm`.`consummer_name` AS `consummer_name`,`comm`.`consummer_identification` AS `consummer_identification`,`comm`.`consummer_email` AS `consummer_email`,`comm`.`consummer_phone` AS `consummer_phone` from (((((`tablita`.`coupon` `c` left join `tablita`.`media_product` `mp` on((`c`.`media_product_id` = `mp`.`media_product_id`))) left join `tablita`.`product` `p` on((`mp`.`product_id` = `p`.`product_id`))) left join `tablita`.`campaign_product` `cp` on((`c`.`campaign_product_id` = `cp`.`campaign_product_id`))) left join `tablita`.`product` `p2` on((`cp`.`product_id` = `p2`.`product_id`))) left join `tablita`.`consummer` `comm` on((`c`.`consummer_id` = `comm`.`consummer_id`))) where (`c`.`coupon_status` = \'R\') order by `c`.`coupon_id`
